version: '3.8'

services:
  pulsopus_client:
    container_name: pulsopus_client
    build: .
    env_file:
      - .env
    ports:
      - '80:80'
    restart: always
    networks:
      - dev

networks:
  dev:
    driver: bridge
