export const enum EAuthSignType {
    MICROSOFT = 'Microsoft',
    GOOGLE = 'Google',
}

export const enum EAuthStage {
    SIGN_STAGE = 'SIGN_STAGE',
    REQUEST_ACCESS_STAGE = 'REQUEST_ACCESS_STAGE',
    REQUEST_ACCESS_SUCCESS_STAGE = 'REQUEST_ACCESS_SUCCESS_STAGE',
    REQUEST_ACCESS_ERROR_STAGE = 'REQUEST_ACCESS_ERROR_STAGE',
    FORGOT_PASSWORD_STAGE = 'FORGOT_PASSWORD_STAGE',
}
